import type { NextPage } from 'next'
import Head from 'next/head'
import axios from 'axios';
import { useState } from "react";
import TextField from '@mui/material/TextField';
import FormGroup from '@mui/material/FormGroup';
import Button from '@mui/material/Button';
import List from "../Components/List";
import { Typography, useMediaQuery } from '@mui/material';

const Home: NextPage = () => {
    // State variable for the search input.
    const [Input, setInput] = useState("");
    const [infoJson, setinfoJson] = useState({ results: [{ title: "", image: "", summary:"" }] });

    // Breakpoint for small screen
    const isPhone = useMediaQuery("(max-width:600px)");

    const RECIPE_BASE_URL = "https://api.spoonacular.com/recipes/complexSearch?";
  
  const smallButton = {
    fontSize:50,
    m: 1
  }

  const bigButton = {
    fontSize:75,
    m: 2
  }

    // Needs a working key.
    const KEY_URL = "apiKey=c64a2503dcc34f788fe1c33db3122ec2";
  
    // Search function uses axios to make api call.
    function search() {

      axios.get(RECIPE_BASE_URL + KEY_URL + "&addRecipeInformation=true&query=" + Input).then((res) => {
        setinfoJson(res.data);
      });
      console.log(infoJson)
    }
    

  return (
    <div className="Homepage">
      <Head>
        <title>Recipe Renovator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div className="Homepage">
        <Typography sx={isPhone ? smallButton:bigButton} variant="h1">
        Recipe Renovator
        </Typography>
        

      
        <FormGroup >
        <TextField
          id="outlined-basic"
          label="Food"
          variant="outlined"
          inputProps={{ style: { color: '#61dafb' } }}
          focused
          onChange={(e) => {
            setInput(e.target.value);
          }}
          onKeyPress={e => {
            if (e.key === 'Enter') {
              setInput((e.target as HTMLInputElement).value)
              {search()}
            }
          }}
        />
        <Button variant="outlined"
          onClick={e => { search() }}
        >Submit</Button>
        </FormGroup>
      
      <div>
        <p className="searchtext">you searched for {Input}</p>
        <div id="recipe-result">
          <List 
          input={infoJson}/>
        </div>
      </div>
    </div>

    </div>

    
  )
}

export default Home
